# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config|
    config.vm.define :db do |db|
        db.vm.hostname = "mongo"
        db.vm.box = "centos6.7"
        db.vm.network "private_network", ip: "192.168.10.3"
        db.vm.provision :puppet do |puppet|
            puppet.manifests_path = "puppet/manifests"
            puppet.module_path = "puppet/modules"
            puppet.manifest_file  = "mongo.pp"
        end
    end
    config.vm.define :app do |app|
        app.vm.hostname = "app"
        app.vm.box = "centos6.7"
        app.vm.network "private_network", ip: "192.168.10.2"
        app.vm.provision :puppet do |puppet|
            puppet.manifests_path = "puppet/manifests"
            puppet.module_path = "puppet/modules"
            puppet.manifest_file  = "errbit.pp"
            puppet.options = "--ordering=manifest"
        app.vm.provision :ansible do |ansible|
            ansible.playbook = "playbook/deployerrbit.yaml"
            ansible.sudo = true
        end
      end
    end
end
