# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos67"
  config.vm.box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.6.7/vagrant-centos-6.7.box"
  # config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box"
  # config.vm.network "forwarded_port", guest: 80, host: 5000
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  
  config.vm.define :web do |web_config|
    web_config.vm.hostname = "web.devops"
    web_config.vm.box = "centos67"
    #web_config.vm.forward_port 80, 8080
    web_config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
      puppet.manifest_file  = "web.pp"
    end
  end
  config.vm.define :db do |db_config|
    db_config.vm.hostname = "db.devops"
    db_config.vm.box = "centos67"
    #db_config.vm.forward_port 3306, 3306
    db_config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
      puppet.manifest_file  = "db.pp"
    end
  end
end
