#!/usr/bin/env ansible-playbook
- name: Deploying errbit!
  hosts: app
  sudo: yes
  gather_facts: False
  vars: 
   errbithome: /home/vagrant/errbit
   githuburl: 'https://github.com/errbit/errbit.git'
  tasks:
    - name: GIT clone errbit repository
      git: repo={{ githuburl }} dest={{ errbithome }}

    - name: Update ruby version
      command: rvm install 2.1.0
      environment: 
          PATH: /usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
          rvm_path: /usr/local/rvm

    - name: Bundler thing
      command: gem install bundler
      environment: 
          PATH: /usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.0:/usr/local/rvm/gems/ruby-2.1.0@global
    
    - name: Bundle install 
      command: bundle install 
      environment:
          PATH: /usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.0:/usr/local/rvm/gems/ruby-2.1.0@global
      args:
       chdir: '{{ errbithome }}'
      register: bundleout

    - debug: msg="{{ bundleout.stdout }}"
    
#    - name: SED COMMAND
#      command: sed -i 's/apps.each\ do\ |app|/apps.each\ |app|\ do/g' /home/vagrant/errbit/app/helpers/apps_helper.rb
#
    - name: Bundle exec
      command: bundle exec rake errbit:bootstrap
      args:
       chdir: '{{ errbithome }}'
      environment:
          PATH: /usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.0:/usr/local/rvm/gems/ruby-2.1.0@global
          MONGO_URL: "mongodb://mongouser:passwd123@192.168.10.3:27017/mongotestdb"
      register: dbing

    - debug: msg="{{ dbing.stdout }}"

    - copy: src=start.sh dest=/home/vagrant/errbit/start.sh
    - file: path=/home/vagrant/errbit/start.sh mode=0755
    - file: path=/etc/nginx/sites-enabled/default state=absent
    - copy: src=nginx.conf dest=/etc/nginx/sites-enabled/rails.conf
    - service: name=nginx state=restarted
