#!/usr/bin/env ansible-playbook
- name: Deploying errbit application
  hosts: app
  sudo: yes
  gather_facts: False
  vars: 
   errbithome: /home/vagrant/errbit
   githuburl: 'https://github.com/errbit/errbit.git'
  tasks:
    - name: GIT clone errbit repository
      git: repo={{ githuburl }} dest={{ errbithome }}

    - name: Bundler install with gem
      command: gem install bundler
      environment: 
          PATH: /usr/local/rvm/gems/ruby-2.1.9/bin:/usr/local/rvm/gems/ruby-2.1.9@global/bin:/usr/local/rvm/rubies/ruby-2.1.9/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.9:/usr/local/rvm/gems/ruby-2.1.9@global
    
    - name: Bundle install 
      command: bundle install 
      environment:
          PATH: /usr/local/rvm/gems/ruby-2.1.9/bin:/usr/local/rvm/gems/ruby-2.1.9@global/bin:/usr/local/rvm/rubies/ruby-2.1.9/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.9:/usr/local/rvm/gems/ruby-2.1.9@global
      args:
       chdir: '{{ errbithome }}'
      register: bundleout

    - debug: msg="{{ bundleout.stdout }}"
    
    - name: Bundle exec
      command: bundle exec rake errbit:bootstrap
      args:
       chdir: '{{ errbithome }}'
      environment:
          PATH: /usr/local/rvm/gems/ruby-2.1.9/bin:/usr/local/rvm/gems/ruby-2.1.9@global/bin:/usr/local/rvm/rubies/ruby-2.1.9/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin
          GEM_PATH: /usr/local/rvm/gems/ruby-2.1.9:/usr/local/rvm/gems/ruby-2.1.9@global
          MONGO_URL: "mongodb://siteUserAdmin:admin@192.168.10.3:27017/admin"
      register: dbing

    - debug: msg="{{ dbing.stdout }}"

    - copy: src=start.sh dest=/home/vagrant/errbit/start.sh
    - file: path=/home/vagrant/errbit/start.sh mode=0755
    - file: path=/etc/nginx/sites-enabled/default state=absent
    - copy: src=nginx.conf dest=/etc/nginx/sites-enabled/rails.conf
    - service: name=nginx state=restarted
