#!/usr/bin/env ansible-playbook
- name: Deploying errbit!
  hosts: app.devops 
  sudo: yes
  gather_facts: False
  vars: 
   errbithome: /home/vagrant/errbit
   githuburl: 'https://github.com/errbit/errbit.git'
  tasks:
    - name: GIT clone errbit repository
      git: repo={{ githuburl }} dest={{ errbithome }}

    - name: Bundler thing
      command: /usr/bin/gem install bundler

    - name: Bundle install 
      command: /usr/local/bin/bundle install
      args: 
       chdir: '{{ errbithome }}'
      register: bundleout      

    - debug: msg="{{ bundleout.stdout }}"
    
    - name: Bundle exec
      command: /usr/local/bin/bundle exec rake errbit:bootstrap
      args:
          chdir: '{{ errbithome }}'
      environment: 
          MONGO_URL: "mongodb://mongouser:pass1@192.168.10.3:27017/mongotestdb"
      register: dbing
  
    - debug: msg="{{ dbing.stdout }}"

    - copy: src=start.sh dest=/home/vagrant/errbit/start.sh
    - file: path=/home/vagrant/errbit/start.sh mode=0755
    - file: path=/etc/nginx/sites-enabled/default state=absent
    - copy: src=nginx.conf dest=/etc/nginx/sites-enabled/rails.conf
    - service: name=nginx state=restarted